<?php

declare(strict_types=1);

namespace Nowo\UptimeMonitorBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration tree for {@see UptimeMonitorExtension}.
 */
final class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_uptime_monitor';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        $root        = $treeBuilder->getRootNode();

        $root
            ->children()
                ->booleanNode('enabled')->defaultTrue()->end()
                ->arrayNode('environments')
                    ->prototype('scalar')->end()
                    ->defaultValue(['prod', 'dev', 'test'])
                ->end()
                ->scalarNode('connection')
                    ->info('Doctrine connection name for monitor storage')
                    ->defaultValue('default')
                ->end()
                ->scalarNode('table_prefix')
                    ->info('Optional table name prefix')
                    ->defaultValue('uptime_')
                ->end()
                ->arrayNode('scheduler')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->enumNode('mode')
                            ->values(['scheduler', 'cron', 'messenger'])
                            ->defaultValue('scheduler')
                        ->end()
                        ->scalarNode('tick')
                            ->info('How often the due-check scan runs (scheduler/cron)')
                            ->defaultValue('1 minute')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('checks')
                    ->addDefaultsIfNotSet()
                    ->info('Check execution and reported latency')
                    ->children()
                        ->integerNode('min_latency_ms')
                            ->info('Floor for stored latency (ms); 0 = no floor. Per-monitor override: config.min_latency_ms')
                            ->defaultValue(0)
                            ->min(0)
                        ->end()
                        ->booleanNode('block_private_urls')
                            ->info('Block HTTP monitor URLs targeting private/local networks (SSRF mitigation).')
                            ->defaultTrue()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('retention')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('detail_days')
                            ->info('Days to keep CheckResult detail rows; 0 = infinite (no purge)')
                            ->defaultValue(30)
                            ->min(0)
                        ->end()
                        ->booleanNode('purge_enabled')->defaultTrue()->end()
                    ->end()
                ->end()
                ->arrayNode('aggregates')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('keep_forever')->defaultTrue()->end()
                        ->arrayNode('periods')
                            ->prototype('scalar')->end()
                            ->defaultValue(['hour', 'day', 'month', 'year'])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('multi_tenant')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->scalarNode('header')->defaultValue('X-Uptime-Tenant')->end()
                        ->scalarNode('default_tenant')->defaultValue('main')->end()
                    ->end()
                ->end()
                ->arrayNode('tenants')
                    ->addDefaultsIfNotSet()
                    ->info('Tenant list UI (/tenants). Disable in single-tenant host apps (e.g. nowo-devkit).')
                    ->children()
                        ->booleanNode('list_enabled')
                            ->defaultTrue()
                            ->info('When false, GET /tenants redirects to the default tenant dashboard.')
                        ->end()
                        ->booleanNode('redirect_when_single')
                            ->defaultFalse()
                            ->info('When true and exactly one tenant exists, /tenants redirects to its dashboard.')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('access_checker')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('dashboard_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                            ->info('Required roles for dashboard access. Empty = allow all authenticated users.')
                        ->end()
                        ->arrayNode('manage_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('settings_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('templates')
                    ->addDefaultsIfNotSet()
                    ->info('Twig layout for admin screens (override in templates/bundles/NowoUptimeMonitorBundle/)')
                    ->children()
                        ->scalarNode('layout')
                            ->defaultValue('@NowoUptimeMonitorBundle/layout.html.twig')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('ui')
                    ->addDefaultsIfNotSet()
                    ->info('UI framework for Twig screens: tabler (Nowo default), custom (BEM), bootstrap, or tailwind')
                    ->children()
                        ->enumNode('framework')
                            ->values(['tabler', 'custom', 'bootstrap', 'tailwind'])
                            ->defaultValue('tabler')
                        ->end()
                        ->arrayNode('tabler')
                            ->addDefaultsIfNotSet()
                            ->info('Tabler integration when ui.framework is tabler')
                            ->children()
                                ->booleanNode('skip_cdn')
                                    ->defaultFalse()
                                    ->info('Skip Tabler CDN when the host app already serves Tabler (e.g. nowo-devkit Vite entry)')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('bootstrap')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('css_url')
                                    ->defaultValue('https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css')
                                ->end()
                                ->scalarNode('js_url')
                                    ->defaultValue('https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('tailwind')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('cdn_script')
                                    ->defaultValue('https://cdn.tailwindcss.com')
                                    ->info('Tailwind Play CDN script for prototyping; use a built CSS file in production')
                                ->end()
                                ->scalarNode('css_url')
                                    ->defaultNull()
                                    ->info('Optional compiled Tailwind CSS URL (overrides CDN script when set)')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('dashboard')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->scalarNode('path')->defaultValue('/uptime')->end()
                        ->scalarNode('prefix')->defaultValue('')->end()
                        ->arrayNode('roles')->prototype('scalar')->end()->defaultValue([])->end()
                        ->enumNode('sync')
                            ->values(['polling', 'mercure'])
                            ->defaultValue('polling')
                        ->end()
                        ->integerNode('poll_interval_ms')->defaultValue(30000)->min(1000)->end()
                        ->arrayNode('mercure')
                            ->addDefaultsIfNotSet()
                            ->info('Mercure topics when dashboard.sync is mercure (requires symfony/mercure-bundle)')
                            ->children()
                                ->scalarNode('topic_template')
                                    ->defaultValue('/uptime/{tenant}')
                                    ->info('Topic per tenant; {tenant} is replaced with tenant slug')
                                ->end()
                                ->booleanNode('private')->defaultTrue()->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('status_page')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->scalarNode('path')->defaultValue('/status')->end()
                        ->scalarNode('title')->defaultNull()->info('Override page title; defaults to tenant name')->end()
                        ->booleanNode('show_latency')->defaultTrue()->end()
                    ->end()
                ->end()
                ->arrayNode('notifications')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultFalse()->end()
                        ->integerNode('cooldown_seconds')->defaultValue(300)->min(0)->end()
                        ->arrayNode('email')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultFalse()->end()
                                ->scalarNode('from')->defaultValue('')->end()
                                ->arrayNode('to')->prototype('scalar')->end()->defaultValue([])->end()
                            ->end()
                        ->end()
                        ->arrayNode('webhook')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultFalse()->end()
                                ->scalarNode('url')->defaultValue('')->end()
                            ->end()
                        ->end()
                        ->arrayNode('slack')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultFalse()->end()
                                ->scalarNode('webhook_url')->defaultValue('')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
