nowo_uptime_monitor:
    retention:
        detail_days: 30
    security:
        access_roles: ['ROLE_ADMIN']
        # access_checker: App\Security\MyUptimeMonitorAccessChecker
        allow_unauthenticated: false
        dashboard_roles: ['ROLE_ADMIN']
        manage_roles: ['ROLE_ADMIN']
        settings_roles: ['ROLE_ADMIN']
    ui:
        framework: tabler
        tabler:
            skip_cdn: false
    templates:
        layout: '@NowoUptimeMonitorBundle/layout.html.twig'
    dashboard:
        path: /uptime
        sync: polling
        mercure:
            topic_template: '/uptime/{tenant}'
    status_page:
        enabled: true
        path: /status

when@prod:
    nowo_uptime_monitor:
        checks:
            block_private_urls: true
