checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - "demo/*"
    - "tests/*"
    - "vendor/*"
    - "node_modules/*"
    - "src/Resources/public/*"

build:
  environment:
    php:
      version: 8.2
      ini:
        memory_limit: -1
        'xdebug.mode': coverage

  cache:
    directories:
      - vendor/
      - node_modules/

  tests:
    before:
      - composer validate --strict
      - composer install --no-interaction --prefer-dist --optimize-autoloader
      - pnpm install --frozen-lockfile || pnpm install
    override:
      - command: composer test-coverage
        environment:
          XDEBUG_MODE: coverage
        coverage:
          file: coverage.xml
          format: clover
      - command: pnpm run test
        environment:
          CI: "true"
